worlds:
    galaxy gates:
    - H999OVA79
    - QAAM7ORW3
    - T99XCVSU3
    - X938T1I42
    - BFFL0PSPV
    - 9992HVO7M
    - RFFQ5POSU
    - 9992HVO7H
    - 5993IVMPX
    - 599F01AUV
    - 7991GVPYP
    - 9992HVOOI
    - BFFH3PWZK
    - 7991GVPHS
    - 793VG11JW
    - 844YJUROV
    - H999OVAO0
    - 8442GUNIA
    - I44I9U09J
    - L998NVCF3
    - V99VAVVSW
    - H999OVANQ
    - H999OVA5X
    - H999OVAW0
    - BFFL0PS77
    - 5993IVM0W
    - 9992HVOA2
    - H999OVANL
    - RFPLQFOKD
    - H999OVAOD
    - 593XI1YFI
    - K444PUFZC
    - 844YJUR7Z
    - 5993IVM9O
    - 999EZ1CGS
    - H999OVAUT
    - L99K5V05F
    - 844YJURRC
    - S4Y9TZLUQ
    - K44K4UZWI
    - T99XCVS1O
    - 7983JWNZ4
    - L998NVCPS
    - 999YKWMGD
    - 844YJURAF
    - H999OVAMT
    - W45TDTV9J
    - X938T1IL3
    - L998NVC7C
    - 9992HVORZ
    - 9992HVOC9
    - H999OVA3Q
    - L998NVC6P
    - H999OVA4D
    - BFFL0PSJ2
    - H999OVA4I
    - 9992HVO1J
    - 5993IVM7H
    - K44G7U3PS
    - K444PUFGQ
    - FFFKZPU3B
    - 798CY2FIC
    - H999OVAT6
    - H999OVASR
    - H999OVACH
    - H999OVASM
    - U45SCTWOV
    - K45H7T1T1
    - 844YJURTJ
    - 5993IVM4I
    - H999OVAL6
    - G445QUDW5
    - H999OVAKR
    - J997MVDCH
    - FFFKZPU1R
    - T99XCVSQK
    - YAABWO79W
    - 9992HVO3Q
    - H999OVABU
    - H999OVABP
    - H999OVAIK
    - T99XCVSNQ
    - H999OVA16
    - ZFFFUP4O8
    - 3FFETP6OL
    - U44UFUUXX
    - X99SEWS5A
    - H999OVA9O
    - T99XCVSN8
    - L998NVCTJ
    - X99WBVUZH
    - G445QUD96
    - T99XCVSOI
    - 5993IVM2Y
    - H999OVAXS
    - H999OVAYK
    - 5982IWOA7
    - W44SDUXRC
    - 99X428M2S
    - 9992HVOO5
    - 5993IVMLE
    - H999OVAHS
    - 9992HVO5X
